### ISSUE TITLE
Scrolling the scene view

### ISSUE THREAD

**Issue by DaanRuiter** [Skylines-ModTools/Skylines-ModTools#1]
First of all, this is awesome. Thank you so much for making this.
Secondly, I had a suggestion. Is is possible to stop the game from zooming in/out when scrolling in the scene view/menu.

**Comment by AlexanderDzhoganov** [comment]
Implemented in https://github.com/AlexanderDzhoganov/Skylines-ModTools/commit/c3e69309113ffc5749d20c19464e87749098f0ec
