### ISSUE TITLE
an expanded watch variable collapses when changing

### ISSUE THREAD

**Issue by brittanygh** [Skylines-ModTools/Skylines-ModTools#3]
I'm guessing the reference changes, the scene explorer window collapses it as it changes.
Scenario - was looking at ToolController, NetTool, NetToolControlPoints (there's 3 of them).  Expanded them, and then started building a curve road (3 control points).  Set down the first control point, then as the mouse is moved, the second watched NetControlPoint collapses, so I can't see it's contents.
You can move the mouse over to re-click the expand button, but that mouse movement is constantly changing the 2nd control point :)
Anyhow, keeping it open when the object it points to changes would help.

Plus most awesome mod!  Spending more time with it than the game right now.

**Comment by AlexanderDzhoganov** [comment]
Hm, good point.

**Comment by AlexanderDzhoganov** [comment]
Ok, this took a bit longer than expected but I have made some design changes and made this work + fixed some related issues. [Commit is here](https://github.com/AlexanderDzhoganov/Skylines-ModTools/commit/77947c5ea81848e909a2879e806f46133b2e4564).
